import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// ==================== PDF STYLES ====================
// Register a font (optional, standard fonts work fine)
Font.register({
  family: 'Roboto',
  src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf'
});

const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 11, color: '#333' },
  header: { marginBottom: 20, borderBottomWidth: 2, borderBottomColor: '#111827', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#111827' },
  meta: { fontSize: 9, color: '#6b7280', marginTop: 4 },
  section: { marginBottom: 15 },
  h1: { fontSize: 18, fontWeight: 'bold', marginTop: 15, marginBottom: 6, color: '#2563eb' },
  h2: { fontSize: 15, fontWeight: 'bold', marginTop: 12, marginBottom: 6, color: '#1f2937' },
  h3: { fontSize: 13, fontWeight: 'bold', marginTop: 10, marginBottom: 4, color: '#374151' },
  text: { lineHeight: 1, marginBottom: 6, textAlign: 'justify' },
  bulletPoint: { flexDirection: 'row', marginBottom: 4 },
  bullet: { width: 10, fontSize: 11 },
  bulletText: { flex: 1 },
  codeBlock: { 
    backgroundColor: '#f3f4f6', 
    padding: 10, 
    fontFamily: 'Courier', 
    fontSize: 10, 
    borderRadius: 4, 
    marginVertical: 8 
  },
  table: { display: "table", width: "auto", borderStyle: "solid", borderWidth: 1, borderRightWidth: 0, borderBottomWidth: 0, marginTop: 10, marginBottom: 10 }, 
  tableCol: { borderStyle: "solid", borderWidth: 1, borderLeftWidth: 0, borderTopWidth: 0 }, 
  tableRow: { flexDirection: "row", width: '100%' }, 
  tableHeader: { backgroundColor: '#e5e7eb', fontWeight: 'bold' },
  tableCell: { margin: 5, fontSize: 10 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, textAlign: 'center', color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#e5e7eb', paddingTop: 10 }
});

// ==================== PDF COMPONENT ====================
export const PdfDocument = ({ structuredData, date }) => (
  <Document>
    <Page size="A4" style={pdfStyles.page}>
      {/* Header */}
      <View style={pdfStyles.header}>
        <Text style={pdfStyles.title}>AI Analysis Report</Text>
        <Text style={pdfStyles.meta}>Generated on {date}</Text>
      </View>

      {/* Content */}
      {structuredData.map((item, index) => {
        switch (item.type) {
          case 'header1':
            return <Text key={index} style={pdfStyles.h1}>{item.content}</Text>;
          case 'header2':
            return <Text key={index} style={pdfStyles.h2}>{item.content}</Text>;
          case 'header3':
            return <Text key={index} style={pdfStyles.h3}>{item.content}</Text>;
          case 'text':
            return <Text key={index} style={pdfStyles.text}>{item.content}</Text>;
          case 'unordered':
          case 'ordered':
            return (
              <View key={index} style={pdfStyles.bulletPoint}>
                <Text style={pdfStyles.bullet}>•</Text>
                <Text style={pdfStyles.bulletText}>{item.content}</Text>
              </View>
            );
          case 'code':
            return (
              <View key={index} style={pdfStyles.codeBlock}>
                <Text>{item.code}</Text>
              </View>
            );
          case 'table':
            const colWidth = (100 / item.headers.length) + '%';
            return (
              <View key={index} style={pdfStyles.table}>
                {/* Header Row */}
                <View style={[pdfStyles.tableRow, pdfStyles.tableHeader]}>
                  {item.headers.map((h, i) => (
                    <View key={i} style={[pdfStyles.tableCol, { width: colWidth }]}>
                      <Text style={pdfStyles.tableCell}>{h}</Text>
                    </View>
                  ))}
                </View>
                {/* Data Rows */}
                {item.rows.map((row, rIndex) => (
                  <View key={rIndex} style={pdfStyles.tableRow}>
                    {row.map((cell, cIndex) => (
                      <View key={cIndex} style={[pdfStyles.tableCol, { width: colWidth }]}>
                        <Text style={pdfStyles.tableCell}>{cell}</Text>
                      </View>
                    ))}
                  </View>
                ))}
              </View>
            );
          default:
            return null;
        }
      })}

      {/* Footer */}
      <Text style={pdfStyles.footer}>
        This document was generated by AI Assistant. Content should be verified.
      </Text>
    </Page>
  </Document>
);

// ==================== WORD COMPONENT (HTML) ====================
export const WordDocument = ({ structuredData, date }) => {
  return (
    <html xmlnsO="urn:schemas-microsoft-com:office:office" xmlnsW="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
      <head>
        <meta charSet="utf-8" />
        <title>Export</title>
        <style dangerouslySetInnerHTML={{__html: `
          body { font-family: 'Calibri', 'Arial', sans-serif; line-height: 1.5; color: #000; }
          h1 { color: #2E74B5; font-size: 24pt; border-bottom: 2px solid #2E74B5; padding-bottom: 6pt; margin-top: 24pt; }
          h2 { color: #2E74B5; font-size: 18pt; margin-top: 18pt; }
          h3 { color: #1F4E79; font-size: 14pt; margin-top: 14pt; border-bottom: 1px solid #ddd; padding-bottom: 4pt; }
          p { margin-bottom: 12pt; font-size: 11pt; }
          ul, ol { margin-bottom: 12pt; }
          .code-block { background: #f0f0f0; border: 1px solid #ccc; padding: 10pt; font-family: 'Courier New', monospace; font-size: 9pt; border-radius: 4pt; margin: 10pt 0; }
          table { width: 100%; border-collapse: collapse; margin: 15pt 0; }
          th { background: #4472C4; color: white; padding: 8pt; border: 1px solid #999; text-align: left; }
          td { padding: 8pt; border: 1px solid #999; }
          .footer { margin-top: 50pt; font-size: 9pt; color: #666; text-align: center; border-top: 1px solid #ccc; padding-top: 10pt; }
        `}} />
      </head>
      <body>
        <div className="Section1">
          {structuredData.map((item, index) => {
            switch(item.type) {
              case 'header1': return <h1 key={index}>{item.content}</h1>;
              case 'header2': return <h2 key={index}>{item.content}</h2>;
              case 'header3': return <h3 key={index}>{item.content}</h3>;
              case 'text': return <p key={index}>{item.content}</p>;
              case 'unordered': return <ul key={index}><li>{item.content}</li></ul>;
              case 'ordered': return <ol key={index}><li>{item.content}</li></ol>;
              case 'code': 
                return (
                  <div key={index} className="code-block">
                    <strong>{item.lang.toUpperCase()}</strong><br/>
                    <pre style={{margin:0}}>{item.code}</pre>
                  </div>
                );
              case 'table':
                return (
                  <table key={index}>
                    <thead>
                      <tr>{item.headers.map((h, i) => <th key={i}>{h}</th>)}</tr>
                    </thead>
                    <tbody>
                      {item.rows.map((row, r) => (
                        <tr key={r}>{row.map((cell, c) => <td key={c}>{cell}</td>)}</tr>
                      ))}
                    </tbody>
                  </table>
                );
              default: return null;
            }
          })}
          
          <div className="footer">
            <p>Generated by AI Assistant • {date}</p>
          </div>
        </div>
      </body>
    </html>
  );
};